### ISSUE TITLE
Remove whitespaces from owners array

### ISSUE THREAD

**Issue by dh3wr** [dapnet-core/database-service#11]
See NodeController.java

````
      // Remove whitespaces from owner array entries
        // TODO: Make it work
		//modNode.put(SanitizeUtils.removeWhiteSpacefromArray(modNode.get("owners"));
````
and SanitizeUtils.java
Erste Dinge sind gemacht, aber die Rückgabe der ersetzten Strings als Array im Node Format macht mir Probleme...

Zeilen sind auskommentiert. See b61baded59073d024b9590728868164b9cb32e1a

**Comment by Taronyu** [comment]
Sollte durch das trimValues der JsonUtils bereits erledigt sein.
