### ISSUE TITLE
Get User Roles from Auth API call

### ISSUE THREAD

**Issue by dh3wr** [dapnet-core/database-service#13]
In UserRoles.java sind nicht alle Roles drin und zu Felxibilität vielleicht lieber beim Start durch
![grafik](https://user-images.githubusercontent.com/16710361/45055436-088c6d00-b090-11e8-9cd1-dd441a472ca5.png)
abfragen und merken.

**Comment by Taronyu** [comment]
Das ist nach meinem Refactoring komplett rausgeflogen, ist erst mal obsolet. So wie es vorher angedacht war, hätte ich das aber auch nicht abrufen können, da die Rollen bereits zur Compile-Zeit hätten verfügbar sein müssen.
