### ISSUE TITLE
Refactor paramPath bei allen Controllern

### ISSUE THREAD

**Issue by dh3wr** [dapnet-core/database-service#20]
Ist das wirklich notwendig, bei performPut und performDelete den paramPath zu übergeben? Der ist doch durch die Klassenableitung schon drin, oder?

**Comment by dh3wr** [comment]
Wenn ich das richtig verstehe, ist das ja z.B ``/users`` oder ``/nodes``. Diese Indentität hat doch schon die abgeleitete Klasse, oder?

**Comment by Taronyu** [comment]
Der Parameter wurde gar nicht mehr benutzt, ich hab das mal rausgeworfen.
